### ISSUE TITLE
Add a free license

### ISSUE THREAD

**Issue by pizzamaker** [Gargron/mastodon#1]
Maybe I missed it, but I couldn't find any info on licensing for this project. It would be helpful if you added a LICENSE.md file to clear up any confusion.

I recommend "AGPLv3 or later", which is the same license used by GNU social itself. More info on it: https://en.wikipedia.org/wiki/Affero_General_Public_License

**Comment by Gargron** [comment]
Thanks for making an issue so I don't forget. The README currently says that as this project is under heavy development I'll add a license later. This is mostly because at this stage there's just no point in sharing or copying the code since so much core stuff is still not implemented.

I'll probably use whatever license Discourse is using. That might be the one you suggest.
