### ISSUE TITLE
Better history state when drilling down

### ISSUE THREAD

**Issue by dougalcampbell** [Gargron/mastodon#100]
When you drill down into statuses and such, the only way to go back to your previous view is to use the browser's back button. It's working fine except that when you get back to any timeline view, it puts you back at the top, instead of at whatever scroll position you were at previously.

Example:

 * I view the public timeline
 * I scroll down and find an interesting status by @User1
 * I click on the status to focus on it and its replies.
 * I scroll down in that list and find an interesting reply.
 * I click on the username of @User2 to view her stream
 * After reading a bit, I click my browser's Back button.
   * I am now back at the top of the previous thread.
 * I click Back again.
   * I am now back at the top of my timeline.

It would be nice if navigation could save the timeline scroll position at whatever status was clicked to trigger the state change.

**Comment by Gargron** [comment]
Yeah, that's something I feel is needed too.

Okay so there's a couple vectors to this:

- componentDidMount of the routes dispatches fetch actions for the timelines, so after navigating back, at first the old content is displayed before the action finishes loading and the content is replaced. This is problematic because with infinite scroll, a lot more content could have been loaded before the re-load. So the fetch actions must be modified to not replace previous content but rather only newer items (unshift). When that is implemented, navigating back will at least ensure that as much content is loaded as was before
- we need to manage scroll position in the hashHistory, I'm looking at the react-router-scroll library right now to figure out how that is done

Besides that it would be nice to add a "back" button to the top of the column... That would be easy for the status/thread view as it does not have a heading at all yet. But for the public timeline, that space is already taken by the heading (and clicking it takes you to the top of the list). Adding a second heading would not look very elegant, so I don't know what's the best course of action there.

**Comment by Gargron** [comment]
As of 8698cd3281ac1d699c723a151b14f1e2f2e8b07e the scroll position is preserved when navigating. Left to do is some sort of back button in the UI.
