### ISSUE TITLE
No reply box when you click through from an email

### ISSUE THREAD

**Issue by jimmytidey** [Gargron/mastodon#110]
If you receive an email telling you that you have been mentioned, you click through to a page where you can see the conversation but cannot reply.

**Comment by Gargron** [comment]
Do you think e-mails should link to the UI page (e.g. <https://mastodon.social/#/statuses/54369?_k=wgl3fc>) instead of static page?

**Comment by jimmytidey** [comment]
I like the design of the page you click through to, it would just be nice if there was a reply text area on it. 

Obviously, then it isn't a static page - but it does instantly allow you to see the conversation.

**Comment by Gargron** [comment]
Hm. Probably worth mentioning that the # part of a URL is not sent to the server, so a link like that would not allow you to be redirected correctly in case there was a login step inbetween... There's an option to use "proper" URLs for the UI in JavaScript (hijacking history), but for those to work I would need to make sure that the URL paths used by JavaScript all load the same page in Rails (the page with the UI JavaScript), which seems at least a bit messy.

A lot of this juggling comes from my desire to keep a separation between the parts of Mastodon that are universal (like sign up, settings, and public pages) and the part that is the client (which is the default client but I don't want it to be the One True Client).

Maybe I could add a "View in UI" link to all static pages.

**Comment by jimmytidey** [comment]
I think the main reason I'm going to click on the link in my email is to reply, so that should definitely be an option on the first page you hit I reckon. Could it go to the main UI with the conversation popped up in a modal? 

Isn't the redirect issue going to come up else where? Wouldn't it make sense to allow the login page to redirect to fragments? 

Doesn't rails have a concept of turbolinks or something that are supposed to just handle this (idk Rails at all)?

It's quite hard for me to grok which bits are part of the client and which not.

**Comment by Gargron** [comment]
The client is only the `/` page that mounts a React.js component (`<Mastodon />`).

Right, links and servers can redirect you to URLs with fragments in them. However browsers don't send the fragment part to the server, so let's say you open `https://mastodon.social/#/statuses/54369?_k=wgl3fc` from a link in the e-mail, but you're not logged in, so the site redirects you to login page. The login page saves what URL you came from originally so it can redirect you back, however because fragments are never sent to it, it will just redirect you to `/` instead. That does sound like a problem now. Perhaps I should move the client to something like `/ui/` and then set it up to use real URLs instead of fragments. Although `/ui/` doesn't sound like a very good path name right now, maybe there's a better name for it
