### ISSUE TITLE
How to handle 3rd party apps with OAuth

### ISSUE THREAD

**Issue by Gargron** [Gargron/mastodon#15]
OAuth is great for allowing all sorts of 3rd party apps to flourish around the API, but thinking it through, I am encountering a small obstacle. Each app requires a client ID and secret on the instance it wants to work with (so it needs to be pre-registered). This means that each app needs to be tailored for a specific instance of Mastodon, but it's not like each app could connect to whatever instance the user wanted it to.

How could this be solved?

**Comment by Gargron** [comment]
See #45

**Comment by sean-clayton** [comment]
@Gargron I'm just about to start developing the OAuth part of my app, and looking at your comments on #45 it seems like I can just create an application on instance ABC and it'll work when my users try to auth on instance XYZ as well?

**Comment by Gargron** [comment]
Your app can self-register on instance XYZ so users of XYZ can use it

**Comment by trwnh** [comment]
@Lilja yes, you register an app with `POST /api/v1/apps`: https://docs.joinmastodon.org/methods/apps/#create

see also the client developer guide: https://docs.joinmastodon.org/client/token/#creating-our-application

**Comment by Lilja** [comment]
@trwnh I've read through those pages earlier. I'm still confused. Since it mentions sending a request to `mastodon.example`, making me think I need to substitute it with the actual mastodon instance, thus making that app only available on `mastodon.example` and not `mastodon.world`. 
**As why would `mastodon.world` know the client ID & secret of an app at `mastodon.example`? It would be in another database in another instance, surely it cannot lookup those credentials in another instance?**

The reason I'm asking is because I'm looking to submit this feature to Lemmy and I would really like to understand how it works for mastodon.

**Comment by trwnh** [comment]
@Lilja you register the app on every server separately, yes
