### ISSUE TITLE
URL links from user bios should have target="_blank"

### ISSUE THREAD

**Issue by hach-que** [Gargron/mastodon#178]
Clicking links in user bios currently replaces Mastodon in the tab; these links should have `target="_blank"` instead to open links in a new tab.

**Comment by Gargron** [comment]
Fixed

**Comment by msappir** [comment]
In some cases this seems to be happening right now.
To reproduce, open this profile in the 4th column (via the search box): https://octodon.social/@tcql
Click on the links to his alts - they open the full profile page in the same tab instead of Mastodon.
Correct behavior would presumably be opening the profile in the 4th column in the same tab instead of the profile you're clicking through.
