### ISSUE TITLE
Adding to home screen prevents you from logging in. (iOS)

### ISSUE THREAD

**Issue by mynatt** [Gargron/mastodon#249]
On iOS, adding the site to your home screen (as a web app) will prevent you from logging in through that view. It uses separate cookies from Safari, so at first will show the homepage. Clicking log in opens the page in Safari, but since the cookies are separate, logging in there will not log you in on the web app. Returning to the web app just leads back to the homepage.

A workaround for now (provided by @Skirmisher@mastodon.social) is to add the login page itself to the home screen. You can log in this way, and the cookies will be saved in the web app.

**Comment by Gargron** [comment]
This goes back to #163.

So the main problem with the webapp no-chrome thing is that any links open in Safari, because the no-chrome mode expects only single page apps that change content via JS. That is the case for the web UI that you see after logging in, but not for the login page. So the problem always was that the login page opened Safari instead of letting you into the actual webapp.

What I've tried doing to resolve this is now that `apple-mobile-web-app-capable` tag is only on the logged-in web UI page, and not on any other pages. Hopefully this means that people will only add it to the homescreen after logging in and it'll just work? I don't have an iOS device so I can't check, but it seems to work on my Android.

**Comment by alahmnat** [comment]
That solution doesn't work in iOS because homescreen web apps are sandboxed separately, and don't share cookies or session data with the main Safari browser instance. If you log in using Safari, then add the site to your homescreen, you just end up in a standalone web app container that loads the not-logged-in homepage. Removing `apple-mobile-web-app-capable` from the login screen also breaks the workaround in mynatt's post. Pages that are added to the homescreen without `apple-mobile-web-app-capable` just open back up in Safari, rather than the standalone web app container.

What should work is re-adding `apple-mobile-web-app-capable` to the logged-out homescreen, then putting an onclick handler on the splash page's "LOG IN" button which prevents the default behavior and uses `window.location.url` to open the login page. Since the login process was working when using mynatt's workaround, you shouldn't have to change anything else about how the login process functions.

Alternately, you could put the login form on the homepage :)
