### ISSUE TITLE
Rotating to landscape and back to portrait increases text size. (iOS mobile)

### ISSUE THREAD

**Issue by mynatt** [Gargron/mastodon#250]
To reproduce, open a timeline in portrait, rotate to landscape, and then rotate back to portrait. The text seems to grow only once, but it requires a refresh to clear, and impedes usability. [https://mastodon.social/users/admung/updates/138587](url)

**Comment by alahmnat** [comment]
This also happens when writing a toot (on iOS at least). The page zooms slightly on keyboard focus and the fonts all bump up in size. It makes the scrolling a bit jankier afterward too.

**Comment by Gargron** [comment]
Does anyone have any idea what might be the cause of it? Because I don't. Sounds like it might be a quirk of mobile browsers, but I'm all ears if anybody's got any ideas.

**Comment by marrus-sh** [comment]
You can prevent iOS from changing the text size when you change orientation using `-webkit-text-size-adjust: none;`. This *should* fix the problem?

This property defaults to `auto` mainly to support older pages which don't have mobile layouts. Because Mastodon does, text-size adjustment doesn't need to be happening and it should be totally safe to opt-out. (Different browsers prefix this property differently, ofc; see: [`text-size-adjust` on the MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-size-adjust)).

**Comment by marrus-sh** [comment]
confirming that this fixed the problem for me~
