### ISSUE TITLE
Time-delayed reblogging

### ISSUE THREAD

**Issue by triplefox** [Gargron/mastodon#286]
Reblogging is an opportunity to move a toot back into the public timeline, but if you're active you will tend to reblog something immediately, which only really helps "second degree" relations that follow you but weren't following your reblog target. It's possible to wait patiently and run through your home TL later to do this, but really active users aren't going to find an opening for a batch process like that.

I don't have an idea for the UI on this yet. It might also be the wrong way to think about the intended goal,  which is to add reach to something that you liked.

**Comment by silasary** [comment]
A Tumblr style Queue might be a good way to do this.

**Comment by marrus-sh** [comment]
This is tangential, but adding that boosting fudges with the order of threaded toots (especially since right now there isn't a visual indication of toot threading), and so it might be a good idea to *disable* boosting for first-degree folks (people who follow both you and the target) when it occurs within, say, the first five minutes of posting.

With regards to the Issue at hand, I'm imagining a “Schedule Boost…” button in the `…` dropdown menu.

**Comment by deli73** [comment]
yeah, I also noticed boosting something puts it at the top of my _own_ feed which is pretty silly

**Comment by swaldie** [comment]
Going to consolidate conversation about scheduling boosts/toots into #340.
