### ISSUE TITLE
Graceful handling of downtime (or: missing posts from downtime)

### ISSUE THREAD

**Issue by TazeTSchnitzel** [Gargron/mastodon#290]
I don't really know how Mastodon could really handle this, but nonetheless: Mastodon only recognises posts from other instances that it has been notified of. During downtime (for example, when upgrading the software), Mastodon will miss notifications for new posts from other instances. When it comes back up, it will not be able to catch up on these and will not show them in the timeline, and visiting a user's profile will not show them either, because Mastodon does not retrieve a user's feed when a profile is viewed, it instead only shows posts it has been notified of.

**Comment by TazeTSchnitzel** [comment]
This is particularly annoying because it makes it impossible to interact with posts made on other instances during downtime.

**Comment by TazeTSchnitzel** [comment]
In particular, pieces of a conversation can simply… be missing entirely, from the perspective of a Mastodon instance.

**Comment by TazeTSchnitzel** [comment]
One of Mastodon's listed features is:

> * **Federated thread resolving** If someone you follow replies to a user unknown to the server, the server fetches the full thread so you can view it without leaving the UI

This is great, but I think it'd be worth doing the same when someone replies to a user *known* to the server, too, in case it missed anything.

**Comment by TazeTSchnitzel** [comment]
Relatedly, you can't interact with posts by a user that the instance was never notified of. This is also frustrating.

**Comment by Gargron** [comment]
When Mastodon sends a Salmon to another server, it does so using a Sidekiq background worker. If that fails because the host is unreachable, Sidekiq has an exceptionally good mechanism for retrying. So even if you server was down, it's going to eventually receive Salmons from other Mastodon servers (can't speak for GS on this one).

The default PuSH server for Mastodon installations is Superfeedr. I am not sure how it handles such a situation - does it re-send updates until status 200 or 201 is returned, or does it forget? I'd think that surely it must also have a retry mechanism. GNU social uses a custom-coded PuSH server, again, no idea how they handle that but wouldn't get my hopes up.
