### ISSUE TITLE
Self-replies no longer appear in public timeline

### ISSUE THREAD

**Issue by fpiesche** [Gargron/mastodon#323]
I *think* this is an artifact of the change to exempt replies from the public feed? I just noticed that if you reply to your own toot (e.g. to chain a train of thought without cramming it all into a single toot, as I am wont to do sometimes), the reply - even though it does not tag a user, and thus behaves like self-replies do on Twitter - doesn't appear in the public timeline. Is this intentional?

**Comment by Gargron** [comment]
Not quite intentional, no... I was eager to remove the self-join from the public timeline query (the one that gets the parent post for filtering rules), so currently it's simply filtering by `in_reply_to_id IS NULL`. Perhaps it'd make sense to denormalize that into an additional `in_reply_to_account_id` because that'd allow to filter by `account_id = in_reply_to_account_id` for self-replies.

**Comment by paralithode** [comment]
yeah, I think it would be good for people to be able to join in part way through a tootessay! Maybe it would be good for there to be an icon on toots that are part of a chain? ...I guess I would need to hive that off to another issue? Maybe I will, I guess it's not high priority though :)
