### ISSUE TITLE
When importing a federated user's avatar fails, Mastodon cannot see their account or posts

### ISSUE THREAD

**Issue by TazeTSchnitzel** [Gargron/mastodon#329]
When Mastodon becomes aware of a new post from another instance (say via Salmon, or PubSubHubbub), it creates an account for the user of that post if one doesn't already exist, and adds the post to their account. As part of creating an account, it fetches the user's avatar. However, if something goes wrong here and the avatar can't be imported, then the user's account is not created and their posts are (apparently?) discarded.

The real world inspiration for this issue is [jk@mastodon.social](https://mastodon.social/users/jk), who has a very large avatar which will always fail to be consumed by other Mastodon instances because of its file size (it hits a 2MB limit enforced by Paperclip). Because of that, it is impossible to interact with them from other Mastodon instances, and such instances do not acknowledge this user's existence, because they cannot construct an account for them.

Even if the file size issue were fixed, it would still be better if Mastodon would fail gracefully when it fails to fetch or import avatars. Its lack of doing so already caused another bug, [being unable to see users with *no* avatar](https://github.com/Gargron/mastodon/issues/289).

**Comment by Gargron** [comment]
I think that I might have fixed the issue you referenced, though I have not checked. But you're right, avatar should not hinder an account from being created. I don't really know how to make it an optional validation... Well, I know how to make it validate file size optionally, but not how to make it discard the avatar if it fails to validate instead of discarding the whole record.
