### ISSUE TITLE
Following/Followers/Post counts seem wrong

### ISSUE THREAD

**Issue by csasarak** [Gargron/mastodon#93]
In the GNU Social interface, the information about the number of followers/following or posts either seems outdated or incomplete. This happens in both the Qvitter interface and the original. 
![This screenshot shows an example](https://cloud.githubusercontent.com/assets/190980/19364877/130cb71a-915e-11e6-88f7-b6f1a6e280f8.png)

**Comment by Gargron** [comment]
The follower/followee/posts counts are relative to whatever instance you're looking at because the knowledge is shared between follower and followee, not onlookers. So for example on yours, only 3 people are following me, and I'm not following anyone. It also only knows about my posts since the first person followed me there. On my home instance, where my "canon" profile is, the counts are correct. This is not a bug.
